language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - hhvm

before_script:
    - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source --dev install

script:
    - ls -d src/Symfony/*/* | parallel --gnu --keep-order 'echo "Running {} tests"; phpunit --exclude-group tty,benchmark {};' || exit 1
    - echo "Running tests requiring tty"; phpunit --group tty
